import React, { createContext, useContext, useState, useCallback } from "react";

export type Language = "az" | "ru";

const translations = {
  az: {
    dashboard: "Dashboard",
    transactions: "Tranzaksiyalar",
    reports: "Hesabatlar",
    tasks: "Tapşırıqlar",
    profile: "Profil",
    settings: "Ayarlar",
    integrations: "İnteqrasiyalar",
    help: "Kömək",
    exit: "Çıxış",
    welcome: "Xoş gəlmisiniz",
    businessOverview: "Biznesinizin ümumi görünüşü",
    income: "Gəlir",
    expense: "Xərc",
    profit: "Mənfəət",
    health: "Sağlamlıq",
    good: "Yaxşı",
    recentTransactions: "Son tranzaksiyalar",
    nextPayment: "Növbəti ödəniş",
    aiRecommendation: "AI Tövsiyə",
    pay: "Ödə",
    check: "Yoxla",
    dataEncrypted: "Məlumatlarınız AES-256 ilə şifrələnib",
    aiTip: "Marketinq xərclərinizi 15% azaltsanız, aylıq mənfəətiniz ₼630 arta bilər. Rəqəmsal marketinqə keçid tövsiyə olunur.",
    settingsTitle: "Parametrlər",
    accountSettings: "Hesab və tətbiq ayarları",
    businessInfo: "Biznes məlumatları",
    businessName: "Biznes adı",
    owner: "Sahibkar",
    email: "Email",
    security: "Təhlükəsizlik",
    password: "Şifrə",
    encryption: "Şifrələmə",
    change: "Dəyiş",
    subscription: "Abunəlik",
    plan: "Plan",
    free: "Pulsuz",
    upgrade: "Yüksəlt",
    paymentMethod: "Ödəniş metodu",
    notAdded: "Əlavə edilməyib",
    add: "Əlavə et",
    appSettings: "Tətbiq ayarları",
    language: "Dil",
    theme: "Tema",
    light: "Açıq",
    dark: "Tünd",
    privacy: "Gizlilik",
    dataSharing: "Məlumatların paylaşılması",
    manage: "İdarə et",
    deleteAccount: "Hesabı sil",
    allDataDeleted: "Bütün məlumatlar silinəcək",
    delete: "Sil",
    helpSupport: "Yardım / Dəstək",
    faq: "Tez-tez verilən suallar (FAQ)",
    contact: "Əlaqə",
    write: "Yazın",
    reportProblem: "Problem bildirmə",
    report: "Bildir",
    exportData: "Məlumatları export et (PDF/CSV)",
    deleteConfirmTitle: "Hesabı silmək?",
    deleteConfirmText: "Bu əməliyyat geri qaytarıla bilməz. Bütün məlumatlarınız həmişəlik silinəcək.",
    cancel: "Ləğv et",
    send: "Göndər",
    phone: "Telefon",
    selectCategory: "Kateqoriya seçin",
    bugError: "Xəta / Bug",
    performance: "Performans problemi",
    designIssue: "Dizayn problemi",
    dataLoss: "Məlumat itkisi",
    other: "Digər",
    shortTitle: "Qısa başlıq",
    describeDetail: "Problemi ətraflı izah edin...",
    writeMessage: "Mesajınızı yazın...",
    premium: "Premium",
    premiumDesc: "Biznesinizi növbəti səviyyəyə aparın",
    monthly: "Aylıq",
    yearly: "İllik",
    basicPlan: "Starter",
    basicPrice: "14.99 ₼",
    basicFeatures: ["Gəlir / xərc uçotu", "Vergi vaxtının izlənməsi", "Əsas hesabatlar", "50 əməliyyat / gün", "Stok idarəsi"],
    premiumPlan: "Plus",
    premiumPrice: "23.99 ₼",
    premiumFeatures: ["Başlanğıcdakı hər şey", "AI chatbot (Azərbaycanca)", "120 əməliyyat / gün"],
    businessPlan: "Premium",
    businessPrice: "29.99 ₼",
    businessFeatures: ["Plusda olan hər şey", "Limitsiz istifadəçi", "İşçi idarəetməsi + maaş", "AI tövsiyələr", "250 əməliyyat / gün", "Prioritet müştəri dəstəyi", "Mühasib üçün giriş portalı"],
    currentPlan: "Cari plan",
    choosePlan: "Seç",
    popular: "Ən çox seçilən",
    perMonth: "/ay",
    save20: "20% qənaət",
    loginTitle: "Daxil ol",
    manageYourBusiness: "Biznesinizi idarə edin",
    quickLogin: "Sürətli giriş",
    quickLoginDesc: "Bir kliklə demo hesaba daxil olun",
    wrongCredentials: "Email və ya şifrə yanlışdır",
    bankEncryption: "AES-256 bank səviyyəli şifrələmə",
    user: "İstifadəçi",
    sale: "Satış",
    service: "Xidmət",
    rent: "İcarə",
    utilities: "Kommunal",
    transport: "Nəqliyyat",
    marketing: "Marketinq",
    faqItems: [
      { q: "Hesabımı necə yüksəldə bilərəm?", a: "Profil > Abunəlik bölməsindən 'Yüksəlt' düyməsinə klikləyin." },
      { q: "Məlumatlarımı necə export edə bilərəm?", a: "Ayarlar > 'Məlumatları export et' düyməsinə klikləyin." },
      { q: "Tranzaksiyaları necə import edə bilərəm?", a: "Tranzaksiyalar səhifəsində '+' düyməsinə klikləyin." },
      { q: "Şifrəmi necə dəyişə bilərəm?", a: "Ayarlar > Təhlükəsizlik > 'Dəyiş' düyməsinə klikləyin." },
    ],
  },
  ru: {
    dashboard: "Панель",
    transactions: "Транзакции",
    reports: "Отчёты",
    tasks: "Задачи",
    profile: "Профиль",
    settings: "Настройки",
    integrations: "Интеграции",
    help: "Помощь",
    exit: "Выход",
    welcome: "Добро пожаловать",
    businessOverview: "Обзор вашего бизнеса",
    income: "Доход",
    expense: "Расход",
    profit: "Прибыль",
    health: "Состояние",
    good: "Хорошо",
    recentTransactions: "Последние транзакции",
    nextPayment: "Следующий платёж",
    aiRecommendation: "AI Рекомендация",
    pay: "Оплатить",
    check: "Проверить",
    dataEncrypted: "Ваши данные зашифрованы AES-256",
    aiTip: "Если вы сократите расходы на маркетинг на 15%, ваша ежемесячная прибыль может увеличиться на ₼630.",
    settingsTitle: "Настройки",
    accountSettings: "Настройки аккаунта и приложения",
    businessInfo: "Информация о бизнесе",
    businessName: "Название бизнеса",
    owner: "Владелец",
    email: "Эл. почта",
    security: "Безопасность",
    password: "Пароль",
    encryption: "Шифрование",
    change: "Изменить",
    subscription: "Подписка",
    plan: "План",
    free: "Бесплатно",
    upgrade: "Улучшить",
    paymentMethod: "Способ оплаты",
    notAdded: "Не добавлен",
    add: "Добавить",
    appSettings: "Настройки приложения",
    language: "Язык",
    theme: "Тема",
    light: "Светлая",
    dark: "Тёмная",
    privacy: "Конфиденциальность",
    dataSharing: "Обмен данными",
    manage: "Управлять",
    deleteAccount: "Удалить аккаунт",
    allDataDeleted: "Все данные будут удалены",
    delete: "Удалить",
    helpSupport: "Помощь / Поддержка",
    faq: "Часто задаваемые вопросы (FAQ)",
    contact: "Контакт",
    write: "Написать",
    reportProblem: "Сообщить о проблеме",
    report: "Сообщить",
    exportData: "Экспорт данных (PDF/CSV)",
    deleteConfirmTitle: "Удалить аккаунт?",
    deleteConfirmText: "Это действие необратимо. Все ваши данные будут удалены навсегда.",
    cancel: "Отмена",
    send: "Отправить",
    phone: "Телефон",
    selectCategory: "Выберите категорию",
    bugError: "Ошибка / Баг",
    performance: "Проблема производительности",
    designIssue: "Проблема дизайна",
    dataLoss: "Потеря данных",
    other: "Другое",
    shortTitle: "Краткий заголовок",
    describeDetail: "Опишите проблему подробно...",
    writeMessage: "Напишите сообщение...",
    premium: "Премиум",
    premiumDesc: "Выведите бизнес на новый уровень",
    monthly: "Ежемесячно",
    yearly: "Ежегодно",
    basicPlan: "Стартер",
    basicPrice: "14.99 ₼",
    basicFeatures: ["Учёт доходов / расходов", "Отслеживание налогов", "Базовые отчёты", "1 пользователь", "50 операций / мес", "Управление складом"],
    premiumPlan: "Плюс",
    premiumPrice: "23.99 ₼",
    premiumFeatures: ["Всё из Стартера", "AI чат-бот (на азербайджанском)", "120 операций / мес", "3 пользователя"],
    businessPlan: "Премиум",
    businessPrice: "29.99 ₼",
    businessFeatures: ["Всё из Плюс", "Безлимит пользователей", "Управление сотрудниками + зарплата", "AI рекомендации", "Безлимитные операции", "Приоритетная поддержка", "Портал входа для бухгалтера"],
    currentPlan: "Текущий план",
    choosePlan: "Выбрать",
    popular: "Самый популярный",
    perMonth: "/мес",
    save20: "Экономия 20%",
    loginTitle: "Вход",
    manageYourBusiness: "Управляйте бизнесом",
    quickLogin: "Быстрый вход",
    quickLoginDesc: "Войти в демо аккаунт одним кликом",
    wrongCredentials: "Неверный email или пароль",
    bankEncryption: "AES-256 банковское шифрование",
    user: "Пользователь",
    sale: "Продажа",
    service: "Услуга",
    rent: "Аренда",
    utilities: "Коммунальные",
    transport: "Транспорт",
    marketing: "Маркетинг",
    faqItems: [
      { q: "Как улучшить аккаунт?", a: "Профиль > Подписка > 'Улучшить'." },
      { q: "Как экспортировать данные?", a: "Нажмите 'Экспорт данных' внизу Настроек." },
      { q: "Как импортировать транзакции?", a: "Нажмите '+' на странице Транзакций." },
      { q: "Как сменить пароль?", a: "Настройки > Безопасность > 'Изменить'." },
    ],
  },
} as const;

type StringKeys = Exclude<keyof typeof translations.az, 'faqItems' | 'basicFeatures' | 'premiumFeatures' | 'businessFeatures'>;

export interface Translations extends Record<StringKeys, string> {
  faqItems: { q: string; a: string }[];
  basicFeatures: string[];
  premiumFeatures: string[];
  businessFeatures: string[];
}

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>("az");
  const t = translations[language] as unknown as Translations;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
